In [9]:

# From https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-detail.html
states_url_dict = {}
states_url_dict['Alabama'] = '01'
states_url_dict['Alaska'] = '02'
states_url_dict['Arizona'] = '04'
states_url_dict['Arkansas'] = '05'
states_url_dict['California'] = '06'
states_url_dict['Colorado'] = '08'
states_url_dict['Connecticut'] = '09'
states_url_dict['Delaware'] = '10'
states_url_dict['District of Columbia'] = '11'
states_url_dict['Florida'] = '12'
states_url_dict['Georgia'] = '13'
states_url_dict['Hawaii'] = '15'
states_url_dict['Idaho'] = '16'
states_url_dict['Illinois'] = '17'
states_url_dict['Indiana'] = '18'
states_url_dict['Iowa'] = '19'
states_url_dict['Kansas'] = '20'
states_url_dict['Kentucky'] = '21'
states_url_dict['Louisiana'] = '22'
states_url_dict['Maine'] = '23'
states_url_dict['Maryland'] = '24'
states_url_dict['Massachusetts'] = '25'
states_url_dict['Michigan'] = '26'
states_url_dict['Minnesota'] = '27'
states_url_dict['Mississippi'] = '28'
states_url_dict['Missouri'] = '29'
states_url_dict['Montana'] = '30'
states_url_dict['Nebraska'] = '31'
states_url_dict['Nevada'] = '32'
states_url_dict['New Hampshire'] = '33'
states_url_dict['New Jersey'] = '34'
states_url_dict['New Mexico'] = '35'
states_url_dict['New York'] = '36'
states_url_dict['North Carolina'] = '37'
states_url_dict['North Dakota'] = '38'
states_url_dict['Ohio'] = '39'
states_url_dict['Oklahoma'] = '40'
states_url_dict['Oregon'] = '41'
states_url_dict['Pennsylvania'] = '42'
states_url_dict['Rhode Island'] = '44'
states_url_dict['South Carolina'] = '45'
states_url_dict['South Dakota'] = '46'
states_url_dict['Tennessee'] = '47'
states_url_dict['Texas'] = '48'
states_url_dict['Utah'] = '49'
states_url_dict['Vermont'] = '50'
states_url_dict['Virginia'] = '51'
states_url_dict['Washington'] = '53'
states_url_dict['West Virginia'] = '54'
states_url_dict['Wisconsin'] = '55'
states_url_dict['Wyoming'] = '56'

In [10]:

from urllib import request
import os

xlxs_folder = os.path.join('../', 'data', 'xlsx')
os.makedirs(name=xlxs_folder, exist_ok=True)
format_str = 'http://www2.census.gov/programs-surveys/popest/tables/2010-2019/state/asrh/sc-est2019-sr11h-{}.xlsx'
states_list = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
               'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
               'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
               'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
               'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
               'West Virginia', 'Wisconsin', 'Wyoming']
for state_name, xlsx_num in states_url_dict.items():
    xlsx_url = format_str.format(xlsx_num)
    file_name = xlsx_url.split('/')[-1]
    file_path = os.path.join(xlxs_folder, file_name)
    try:
        request.urlretrieve(xlsx_url, file_path)
    except Exception as e:
        print(f'{file_name} is getting an error: {str(e).strip()}')

In [70]:

!start %windir%\explorer.exe "{os.path.abspath(os.path.dirname(file_path))}"

In [67]:

import random
import pandas as pd

columns_list = ['TOTAL_POPULATION', 'White', 'Black_or_African_American', 'American_Indian_and_Alaska_Native', 'Asian',
                'Native_Hawaiian_and_Other_Pacific_Islander', 'Two_or_More_Races']
added_columns_list = ['State_Name'] + columns_list
state_race_year_df = pd.DataFrame([], columns=added_columns_list)
for state_str in states_list:
    xlsx_num = states_url_dict[state_str]
    file_name = f'sc-est2019-sr11h-{xlsx_num}.xlsx'
    file_path = os.path.join(xlxs_folder, file_name)
    df = pd.read_excel(file_path).drop([0, 1]+list(range(11, 135)), axis='index')
    df.columns = [str(cn).split('.')[0] for cn in df.iloc[0].tolist()]
    df = df.drop([2], axis='index').set_index('nan').T
    df.columns = [cn.replace('.', ' ').replace(':', ' ').strip().replace(' ', '_') for cn in df.columns.tolist()]
    df = df[columns_list]
    df['State_Name'] = state_str
    df = df[added_columns_list]
    state_race_year_df = pd.concat([state_race_year_df, df])
state_race_year_df = state_race_year_df.reset_index().rename(columns={'index': 'Year'}).set_index(['Year', 'State_Name'])

In [68]:

state_race_year_df.head(20).T.head(6).T

,,TOTAL_POPULATION,White,Black_or_African_American,American_Indian_and_Alaska_Native,Asian,Native_Hawaiian_and_Other_Pacific_Islander
Year,State_Name,,,,,,
Census,Alabama,4779736,3362877,1259224,32903,55240,5208
Estimates Base,Alabama,4780125,3363091,1259399,32903,55240,5208
2010,Alabama,4785437,3365559,1261234,32883,55721,5167
2011,Alabama,4.79907e+06,3.36925e+06,1.26698e+06,32793,57527,5030
2012,Alabama,4.81559e+06,3.37106e+06,1.27563e+06,32863,60785,4970
2013,Alabama,4.83008e+06,3.3722e+06,1.28434e+06,32896,63011,4901
2014,Alabama,4.8418e+06,3.37336e+06,1.29058e+06,33095,64943,4911
2015,Alabama,4.85235e+06,3.37234e+06,1.29731e+06,33332,67141,4916
2016,Alabama,4.86352e+06,3.37411e+06,1.30164e+06,33610,69476,4916
2017,Alabama,4.87449e+06,3.37653e+06,1.30562e+06,33840,71245,4961
2018,Alabama,4.88768e+06,3.38164e+06,1.30957e+06,34281,72354,5048
2019,Alabama,4.90318e+06,3.3894e+06,1.31329e+06,34799,73715,5110
Census,Alaska,710231,483873,24441,106268,38882,7662
Estimates Base,Alaska,710249,483883,24442,106271,38885,7662
2010,Alaska,713910,485960,24633,106713,39284,7762
2011,Alaska,722128,489454,25366,108090,40645,8118
2012,Alaska,730443,492838,26506,109278,42087,8639
2013,Alaska,737068,494783,27186,110542,43737,9083
2014,Alaska,736283,492186,26975,111450,44331,9179
2015,Alaska,737498,490845,27019,112416,45254,9424

In [71]:

%run ../load_magic/storage.py
s = Storage()

In [72]:

s.save_dataframes(include_index=True, state_race_year_df=state_race_year_df)

Saving to C:\Users\dev\Documents\Repositories\StatsByCountry\saves\csv\state_race_year_df.csv